### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tigerninjaman** [nmarinsek/burst_detection#3]
When installing using `pip install burst_detection`  I get the error `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 199: character maps to <undefined>` (it looks to be an issue in setup.py when reading the README.rst). After downloading the .zip file, I did `python setup.py install`, and got a few syntax errors within setup.py: missing `'` in line 13; missing `,` in line 19, and then once again the decoding error. Changing line 11 in setup.py to `long_description = 'Error'` solved the problem, and it was able to install. This post is mostly for letting you know that there is a decoding issue when reading README.rst, and some minor syntax errors in setup.py.

For reference, I am using python 3.6 on Windows 10.

**Comment by jwc19890114** [comment]
I have encountered the same problem.
It may be the encoding set. But I did not solve this one.

**Comment by tigerninjaman** [comment]
jwc, did you try my suggestion?
You should download the .zip file for burst_detection. Then open setup.py and fix the missing `'` in line 13 and the missing `,` in line 19, and change line 11 to `long_description = 'Error'`. Then open up your terminal and `cd` into burst_detection, and enter `python setup.py install`. 
This should fix your issue.

**Comment by tigerninjaman** [comment]
jwc, it looks like the most recent commit (25 days ago) fixed all the issues and typos I noted. Have you tried downloading the .zip file, changing line 11 to `long_description = 'Error'`, and then `cd`ing into burst_detection and running `python setup.py install`? I am closing this issue, as my original comment has been addressed.

**Comment by LucyTishkina** [comment]
I am on Windows 10 and pip install still gives the codec error. The suggested work around does work successfully.
